export type PricingPreset = {
  presetKey: string;
  name: string;
  category: string;
  description: string;
  tag?: string;
  price: number;
  expiryMonths: number;
  durationLabel?: string;
  billingLabel?: string;
  availabilityNote?: string;
  featureBullets: string[];
  sortOrder: number;
  vivaMinutes?: number;
};

export const frcsPricingPresets: PricingPreset[] = [
  {
    presetKey: "core-viva-6m",
    name: "Urologics CORE Viva",
    category: "FRCS Urology Section 2",
    description: "Structured live preparation for candidates who want lectures, viva practice, and full recordings.",
    tag: "Core Track",
    price: 799,
    expiryMonths: 6,
    durationLabel: "6 Months",
    billingLabel: "£130/month",
    featureBullets: ["Live Lectures + Viva Practice", "Full Recordings Access"],
    sortOrder: 10,
  },
  {
    presetKey: "core-viva-12m",
    name: "Urologics CORE Viva",
    category: "FRCS Urology Section 2",
    description: "Extended access to the CORE viva pathway with the same structured prep over a full year.",
    tag: "Core Track",
    price: 1199,
    expiryMonths: 12,
    durationLabel: "12 Months",
    billingLabel: "£99/month",
    featureBullets: ["Live Lectures + Viva Practice", "Full Recordings Access"],
    sortOrder: 11,
  },
  {
    presetKey: "elite-viva-6m",
    name: "Urologics ELITE Viva",
    category: "FRCS Urology Section 2",
    description: "The ELITE viva package adds AI mock minutes on top of the full live and recorded experience.",
    tag: "Popular",
    price: 1199,
    expiryMonths: 6,
    durationLabel: "6 Months",
    billingLabel: "£199/month",
    featureBullets: [
      "Live Lectures + Viva Practice",
      "Full Recordings Access",
      "AI Viva Mock (500 minutes)",
    ],
    sortOrder: 20,
    vivaMinutes: 500,
  },
  {
    presetKey: "elite-viva-12m",
    name: "Urologics ELITE Viva",
    category: "FRCS Urology Section 2",
    description: "The longest ELITE pathway with year-long access and integrated AI viva preparation.",
    tag: "Best Value",
    price: 1499,
    expiryMonths: 12,
    durationLabel: "12 Months",
    billingLabel: "£125/month",
    featureBullets: [
      "Live Lectures + Viva Practice",
      "Full Recordings Access",
      "AI Viva Mock (500 minutes)",
    ],
    sortOrder: 21,
    vivaMinutes: 500,
  },
  {
    presetKey: "ai-viva-3m",
    name: "Urologics AI Viva",
    category: "FRCS Urology Section 2",
    description: "Dedicated AI viva practice for candidates who want focused simulation without the full lecture track.",
    tag: "AI Practice",
    price: 499,
    expiryMonths: 3,
    durationLabel: "3 Months",
    featureBullets: ["AI-Based Viva Practice (500 minutes)"],
    sortOrder: 30,
    vivaMinutes: 500,
  },
  {
    presetKey: "ai-viva-6m",
    name: "Urologics AI Viva",
    category: "FRCS Urology Section 2",
    description: "Longer AI viva access for repeated practice and refinement before the exam.",
    tag: "AI Practice",
    price: 799,
    expiryMonths: 6,
    durationLabel: "6 Months",
    featureBullets: ["AI-Based Viva Practice (500 minutes)"],
    sortOrder: 31,
    vivaMinutes: 500,
  },
  {
    presetKey: "viva-in-dreams-1",
    name: "Urologics Viva in Dreams",
    category: "FRCS Urology Section 2",
    description: "High-touch face-to-face online mock exam practice for realistic viva pressure testing.",
    price: 349,
    expiryMonths: 1,
    durationLabel: "1 Mock",
    availabilityNote: "Limited slots only",
    featureBullets: ["Face-to-Face Online Mock Exam"],
    sortOrder: 40,
  },
  {
    presetKey: "viva-in-dreams-2",
    name: "Urologics Viva in Dreams",
    category: "FRCS Urology Section 2",
    description: "Two full mock exams for candidates who want repeated live performance feedback.",
    price: 649,
    expiryMonths: 2,
    durationLabel: "2 Mocks",
    availabilityNote: "Limited slots only",
    featureBullets: ["Face-to-Face Online Mock Exam"],
    sortOrder: 41,
  },
  {
    presetKey: "executive-mentorship-8",
    name: "Urologics EXECUTIVE Mentorship",
    category: "FRCS Urology Section 2",
    description: "Personalized one-to-one mentorship delivered in live online sessions.",
    tag: "Mentorship",
    price: 899,
    expiryMonths: 2,
    durationLabel: "8 Sessions",
    availabilityNote: "Limited slots only",
    featureBullets: ["One to one live online sessions"],
    sortOrder: 50,
  },
  {
    presetKey: "executive-mentorship-16",
    name: "Urologics EXECUTIVE Mentorship",
    category: "FRCS Urology Section 2",
    description: "The deepest mentorship option for candidates who want repeated one-to-one support.",
    tag: "Mentorship",
    price: 1899,
    expiryMonths: 4,
    durationLabel: "16 Sessions",
    availabilityNote: "Limited slots only",
    featureBullets: ["One to one live online sessions"],
    sortOrder: 51,
  },
  {
    presetKey: "supreme-frcs-6m",
    name: "Urologics SUPREME FRCS Program",
    category: "Combined Section 1 + Section 2",
    description: "Combined FRCS pathway with Urologics ELITE SBA plus Urologics ELITE Viva.",
    tag: "Combined",
    price: 1199,
    expiryMonths: 6,
    durationLabel: "6 Months",
    billingLabel: "£199/month",
    featureBullets: ["Urologics ELITE SBA", "Urologics ELITE Viva"],
    sortOrder: 60,
  },
  {
    presetKey: "supreme-frcs-12m",
    name: "Urologics SUPREME FRCS Program",
    category: "Combined Section 1 + Section 2",
    description: "The longest combined program for candidates who want both Section 1 and Section 2 coverage.",
    tag: "Combined",
    price: 1799,
    expiryMonths: 12,
    durationLabel: "12 Months",
    billingLabel: "£149/month",
    featureBullets: ["Urologics ELITE SBA", "Urologics ELITE Viva"],
    sortOrder: 61,
  },
];
